FROM nginx:bookworm

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y iproute2

# Copy the custom nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the custom entrypoint script
COPY custom-entrypoint.sh /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh

# Use the custom entrypoint script
ENTRYPOINT ["/custom-entrypoint.sh"]

# Default command to start Nginx
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80