FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt update && apt install -y iproute2 python3 python3-pip

# Copy the traffic generator script into the container
COPY traffic_generator.py /traffic_generator.py

# Set the default command
CMD ["bash"]