# multi_net_container/Dockerfile
FROM nginx:bookworm

ENV DEBIAN_FRONTEND=noninteractive

# Install required tools
RUN apt-get update && apt-get install -y \
    iproute2 \
    iptables \
    net-tools \
    curl \
    iputils-ping \
    tcpdump \
    rsyslog \
    && rm -rf /var/lib/apt/lists/*

RUN echo "kern.*    /var/log/kern/kern.log" >> /etc/rsyslog.d/10-kernlog.conf
RUN mkdir /var/log/kern
RUN touch /var/log/kern/kern.log
RUN chmod 644 /var/log/kern/kern.log

# Reverse proxy
COPY nginx.conf /etc/nginx/
COPY reverse-proxy /etc/nginx/sites-available/reverse-proxy
RUN mkdir /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/reverse-proxy /etc/nginx/sites-enabled/

# Enable IP forwarding and setup NAT on startup
COPY router.sh /router.sh
RUN chmod +x /router.sh

CMD ["/router.sh"]
