# multi_net_container/Dockerfile
FROM nginx:bookworm

ENV DEBIAN_FRONTEND=noninteractive

# Install required tools
RUN apt-get update && apt-get install -y \
    iproute2 \
    iptables \
    net-tools \
    curl \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Reverse proxy
COPY reverse-proxy /etc/nginx/sites-available/reverse-proxy
# RUN ln -s /etc/nginx/sites-available/reverse-proxy /etc/nginx/sites-enabled/

# Enable IP forwarding and setup NAT on startup
COPY router.sh /router.sh
RUN chmod +x /router.sh

CMD ["/router.sh"]
