services:

  router:
    build: ./router
    cap_add:
      - NET_ADMIN
    hostname: router
    container_name: router
    networks:
      internal_net:
        ipv4_address: 172.28.0.2
      external_net:
        ipv4_address: 172.30.0.2
    volumes:
      - nginx_logs:/var/log/nginx
      - net_logs:/tmp/router_logs
    privileged: true
  router_uf:
    build: ./router_uf
    container_name: router_uf
    hostname: router_uf
    networks:
      internal_net:
        ipv4_address: 172.28.0.6
    volumes:
      - nginx_logs:/nginx-logs:ro
      - net_logs:/net-logs:ro
    user:
      root
  attacker:
    build: ./attacker
    image: network-attacker:latest
    hostname: attacker
    container_name: attacker
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.33

  attacker2:
    build: ./attacker
    image: network-attacker:latest
    hostname: attacker2
    container_name: attacker2
    command: sleep infinity
    networks:
      internal_net:
        ipv4_address: 172.28.0.13

  webserver:
    build: ./webserver
    cap_add:
      - NET_ADMIN
    hostname: webserver
    container_name: webserver
    networks:
      internal_net:
        ipv4_address: 172.28.0.3
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      /docker-entrypoint.sh nginx -g 'daemon off;'"
    volumes:
      - webserver_logs:/var/log/nginx
  webserver_uf:
    build: ./webserver_uf
    container_name: webserver_uf
    hostname: webserver_uf
    networks:
      internal_net:
        ipv4_address: 172.28.0.4
    volumes:
      - webserver_logs:/nginx-logs:ro
    user:
      root
  dns:
    image: andyshinn/dnsmasq
    entrypoint: []
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 172.28.0.21
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
    volumes:
      - dns_logs:/dns-logs
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      dnsmasq -k --log-facility=/dns-logs/dnsmasq.log --log-queries"
  dns_uf:
    build: ./dns_uf
    container_name: dns_uf
    hostname: dns_uf
    networks:
      internal_net:
        ipv4_address: 172.28.0.5
    volumes:
      - dns_logs:/dns-logs:ro
    user:
      root
  splunk:
    build: ./splunk
    hostname: splunk
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=netsec25
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC endpoint
      - "9997:9997"   # UF
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.100
    healthcheck:
      test: curl -f http://localhost:8000 || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
  user1:
    build: ./external_user
    image: network-external_user:latest
    hostname: user1
    container_name: user1
    cap_add:
      - NET_ADMIN
    networks:
      external_net:
        ipv4_address: 172.30.0.4
    command: sh -c 'sleep 10 && python3 /traffic_generator.py && sleep infinity'
  user2:
    build: ./external_user
    image: network-external_user:latest
    hostname: user2
    container_name: user2
    cap_add:
      - NET_ADMIN
    networks:
      external_net:
        ipv4_address: 172.30.0.5
    command: sh -c 'sleep 10 && python3 /traffic_generator.py && sleep infinity'
  user3:
    build: ./external_user
    image: network-external_user:latest
    hostname: user3
    container_name: user3
    cap_add:
      - NET_ADMIN
    networks:
      external_net:
        ipv4_address: 172.30.0.6
    command: sh -c 'sleep 10 && python3 /traffic_generator.py && sleep infinity'
  internal_user1:
    build: ./internal_user
    image: network-internal_user:latest
    hostname: internal_user1
    container_name: internal_user1
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.10
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      sleep 10 && python3 /traffic_generator.py &&
      tail -f /dev/null"
  internal_user2:
    build: ./internal_user
    image: network-internal_user:latest
    hostname: internal_user2
    container_name: internal_user2
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.11
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      sleep 10 && python3 /traffic_generator.py &&
      tail -f /dev/null"
  internal_user3:
    build: ./internal_user
    image: network-internal_user:latest
    hostname: internal_user3
    container_name: internal_user3
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.12
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      sleep 10 && python3 /traffic_generator.py &&
      tail -f /dev/null"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  webserver_logs:
  dns_logs:
  nginx_logs:
  net_logs:
