services:

  router:
    build: ./router
    cap_add:
      - NET_ADMIN
    hostname: router
    container_name: router
    networks:
      internal_net:
        ipv4_address: 172.28.0.2
      external_net:
        ipv4_address: 172.30.0.2

  attacker:
    build: ./attacker
    hostname: attacker
    container_name: attacker
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.3

  webserver:
    build: ./webserver
    cap_add:
      - NET_ADMIN
    hostname: webserver
    container_name: webserver
    networks:
      internal_net:
        ipv4_address: 172.28.0.3
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      tail -f /dev/null"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
