services:

  router:
    build: ./router
    cap_add:
      - NET_ADMIN
    hostname: router
    container_name: router
    networks:
      internal_net:
        ipv4_address: 172.28.0.2
      external_net:
        ipv4_address: 172.30.0.2

  attacker:
    build: ./attacker
    hostname: attacker
    container_name: attacker
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.3

  webserver:
    build: ./webserver
    cap_add:
      - NET_ADMIN
    hostname: webserver
    container_name: webserver
    networks:
      internal_net:
        ipv4_address: 172.28.0.3
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      /docker-entrypoint.sh nginx -g 'daemon off;'"

  dns:
    image: andyshinn/dnsmasq
    entrypoint: []
    container_name: dns
    networks:
      internal_net:
        ipv4_address: 172.28.0.21
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      dnsmasq -k --log-facility=-"

  splunk:
    build: ./splunk
    hostname: splunk
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC endpoint
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.4
    healthcheck:
      test: curl -f http://localhost:8000 || exit 1
      interval: 60s
      timeout: 10s
      retries: 5

  user1:
    image: ubuntu
    hostname: user1
    container_name: user1
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.4
  user2:
    image: ubuntu
    hostname: user2
    container_name: user2
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.5
  user3:
    image: ubuntu
    hostname: user3
    container_name: user3
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 172.30.0.6

  internal_user1:
    build: ./internal_user
    hostname: internal_user1
    container_name: internal_user1
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.10
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      tail -f /dev/null"
  internal_user2:
    build: ./internal_user
    hostname: internal_user2
    container_name: internal_user2
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.11
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      tail -f /dev/null"
  internal_user3:
    build: ./internal_user
    hostname: internal_user3
    container_name: internal_user3
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 172.28.0.12
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      tail -f /dev/null"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
