FROM splunk/splunk:latest

USER root

RUN microdnf update -y && microdnf install -y iproute

COPY entrypoint-wrapper.sh /entrypoint-wrapper.sh
RUN chmod +x /entrypoint-wrapper.sh

ENTRYPOINT ["/entrypoint-wrapper.sh"]
