FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    curl nmap iputils-ping netcat-openbsd dnsutils \
    hping3 sqlmap \
    python3 python3-pip python3-scapy \
    tcpdump libpcap-dev \
    && apt clean

WORKDIR /opt
COPY ddos.py .

COPY arp.py .
COPY port.py .
COPY ping.py .

CMD ["bash"]
